Slince\Shopify\Manager\Order\ShippingLine:
    properties:
        id:
            type: integer
        code:
            type: string
        price:
            type: float
        price_set:
            type: object
        discounted_price:
            type: float
        discounted_price_set:
            type: object
        source:
            type: string
        title:
            type: string
        taxLines:
            type: array<Slince\Shopify\Manager\Order\TaxLine>
        carrierIdentifier:
            type: string
        requestedFulfillmentServiceId:
            type: string



