Slince\Shopify\Manager\Order\ShippingLine:
    properties:
        id:
            type: integer
        code:
            type: string
        price:
            type: float
        price_set:
            type: Slince\Shopify\Manager\PriceSet\PriceSet
        priceSet:
            type: Slince\Shopify\Manager\PriceSet\PriceSet
        discounted_price:
            type: float
        discountedPrice:
            type: float
        discounted_price_set:
            type: string
        discountedPriceSet:
            type: Slince\Shopify\Manager\PriceSet\PriceSet
        source:
            type: string
        title:
            type: string
        taxLines:
            type: array<Slince\Shopify\Manager\Order\TaxLine>
        carrierIdentifier:
            type: string
        requestedFulfillmentServiceId:
            type: string



