Slince\Shopify\Manager\Order\DiscountAllocation:
    properties:
        amount:
            type: string
        discountApplicationIndex:
            type: integer
        amountSet:
            type: Slince\Shopify\Manager\PriceSet\PriceSet