Slince\Shopify\Manager\Order\OriginLocation:
    properties:
        countryCode:
            type: string
        provinceCode:
            type: string
        name:
            type: string
        address1:
            type: string
        address2:
            type: string
        city:
            type: string
        zip:
            type: string
